- name: configure the backend server
  hosts: backend
  become: yes
  tasks:
  - name: disable current nodejs
    ansible.builtin.command: dnf module disable nodejs -y

  - name: enable nodejs 20
    ansible.builtin.command: dnf module enable nodejs:20 -y

  - name: install nodejs
    ansible.builtin.package:
     name: nodejs
     state: present

  - name: creating the user
    ansible.builtin.user:
     name: Expense

  - name: creating the app directory
    ansible.builtin.file:
     path: /app
     state: directory
  
  - name: download the code
    ansible.builtin.get_url:
     url: https://expense-builds.s3.us-east-1.amazonaws.com/expense-backend-v2.zip
     path: /tmp/backend.zip

  - name: unzipping the code
    ansible.builtin.unarchive:
     src: /tmp/backend.zip
     dest: /app

     